apiVersion: apps/v1
kind: Deployment
metadata:
  name: ldap-auth-be-deploy
  labels:
    tier: back-end
    app: ldap-auth-app
spec:
  selector:
    matchLabels:
      tier: back-end
      app: ldap-auth-app
  replicas: 4
  template:
    metadata:
      name: ldap-auth-be-pod
      labels:
        tier: back-end
        app: ldap-auth-app
    spec:
      containers:
        - name: ldap-be
          image: sangpn1/ldap-be:latest
