version: "3.7"
services:
  front-end:
    build: ./fe/
    hostname: front-end
    depends_on:
      - back-end
    ports:
      - 80:80
    networks:
      - ldap
  back-end:
    build: ./be/
    hostname: back-end
    networks:
      - ldap
    depends_on:
      - db
  db:
    image: phpmyadmin/phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=123
    networks:
      - ldap
    ports:
      - 9000:80
networks:
  ldap:
    driver: bridge
