version: "3"
services:
  front-end:
    build: ./fe/
    hostname: front-end
    ports:
      - 80:80
    networks:
      - ldap
  back-end:
    build: ./be/
    hostname: back-end
    networks:
      - ldap
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    networks:
      - ldap
    ports:
      - 5432:5432
networks:
  ldap:
    driver: bridge
